Moved Declaration of dynamic content from Makefile to .env file for Equinix-Metal
gardener/machine-controller-manager-provider-equinix-metal pull request #21
Opened 2023-10-18 09:27 UTC by piyuagr

**What this PR does / why we need it**:
This PR updates Makefile content to import dynamic content from the .env file.

**Which issue(s) this PR fixes**:
Fixes -> https://github.com/gardener/machine-controller-manager/issues/846

**Special notes for your reviewer**:

**Release note**:

```feature user
NONE
```

2023-10-18 09:39 UTC, schrodit approved these changes
/lgtm

2023-10-26 04:24 UTC, himanshu-kun requested changes

2023-10-26 04:24 UTC, himanshu-kun commented on Makefile
> +-include .env
include directives should be the first lines in the file, after the copyright.. kindly update

2023-10-26 04:31 UTC, himanshu-kun approved these changes
/lgtm

2023-10-30 05:41 UTC, merged